### ISSUE TITLE
[feature request] - close button on shop pop-up

### ISSUE THREAD

**Issue by IanCStewart** [anchorchat/react-stickerpipe#12]
i would like to close the shop preview after viewing it
<img width="629" alt="screen shot 2016-11-30 at 09 39 33" src="https://cloud.githubusercontent.com/assets/14125280/20745346/3ea46366-b6e1-11e6-9aaa-f006406f1781.png">

**Comment by sjaakluthart** [comment]
Yes! Sounds good, go ahead and implement it. Be sure to create a react component for the icon you want. 😊

**Comment by sjaakluthart** [comment]
https://github.com/anchorchat/react-stickerpipe/commit/32ff422407cb0a1bedcc0d8203db082b3910a407
