### ISSUE TITLE
I want to be able to open the stickershop in a dialog. 

### ISSUE THREAD

**Issue by svenjens** [anchorchat/react-stickerpipe#25]
I want to be able to open the stickershop in a dialog. Because if i open the shop, i can't see the shop is open. 
<img width="1308" alt="schermafbeelding 2016-12-07 om 17 38 17" src="https://cloud.githubusercontent.com/assets/4559966/20976843/14f49eaa-bca4-11e6-8e75-5f0083ff9bab.png">

**Comment by sjaakluthart** [comment]
We could also replace the current pack with the shop
