### ISSUE TITLE
Allow custom styling on components

### ISSUE THREAD

**Issue by larstadema** [anchorchat/react-stickerpipe#34]
When importing the main component in the project, I would like to be able to add custom styling.

```
<StickerMenu shopStyle={shopStyle} packStyle={packStyle} shopStyle={shopStyle} /> 
```

All you have to do in the component is merge the default styles with the given props.

`<StickerShop style={{...this.props.shopStyle, ...style}}>`

**Comment by sjaakluthart** [comment]
You can style the component with css or scss, we've added classNames for this.
